### ISSUE TITLE
Icons not align correctly

### ISSUE THREAD

**Issue by maxjf1** [iondrimba/pwa-music-player#125]
Some icons are not aligned correctly:
![image](https://user-images.githubusercontent.com/6114888/86142974-398e2b00-baca-11ea-9238-402828643478.png)
![image](https://user-images.githubusercontent.com/6114888/86142993-414dcf80-baca-11ea-8887-49f3f95e9b71.png)

Applying `align-items: center;` to the buttons seems to fix it :smile: 

Using Ubuntu 20.04 and Chrome 83.0.4103.116 64 bits. 

Great app by the way :sunglasses:

**Comment by iondrimba** [comment]
Hey @maxjf1 thanks for letting me know, I will look into to that :+1: :medal_military:

**Comment by iondrimba** [comment]
@maxjf1 Issue fixed, try doing a hard refresh 👍
